<?php class GProductCategory {
	function __construct(){
		$this->categories = array(
			array("469", "Saúde e beleza"),
			array("491", "Saúde e beleza", "Cuidados com a saúde"),
			array("5071", "Saúde e beleza", "Cuidados com a saúde", "Acessórios para monitor biométrico"),
			array("6284", "Saúde e beleza", "Cuidados com a saúde", "Acessórios para monitor biométrico", "Acessórios de monitoramento da pressão arterial"),
			array("6285", "Saúde e beleza", "Cuidados com a saúde", "Acessórios para monitor biométrico", "Acessórios de monitoramento da pressão arterial", "Braceletes de monitoramento da pressão arterial"),
			array("5072", "Saúde e beleza", "Cuidados com a saúde", "Acessórios para monitor biométrico", "Acessórios para balança de banheiro"),
			array("3688", "Saúde e beleza", "Cuidados com a saúde", "Acessórios para monitor biométrico", "Acessórios para medição de glicose"),
			array("3111", "Saúde e beleza", "Cuidados com a saúde", "Acessórios para monitor biométrico", "Acessórios para medição de glicose", "Lancetadores"),
			array("6323", "Saúde e beleza", "Cuidados com a saúde", "Acessórios para monitor biométrico", "Acessórios para medição de glicose", "Solução de controle da glicose no sangue"),
			array("3905", "Saúde e beleza", "Cuidados com a saúde", "Acessórios para monitor biométrico", "Acessórios para medição de glicose", "Tiras para teste de glicose"),
			array("505819", "Saúde e beleza", "Cuidados com a saúde", "Acessórios para monitor biométrico", "Acessórios para monitores de atividade"),
			array("5849", "Saúde e beleza", "Cuidados com a saúde", "Acupuntura"),
			array("5851", "Saúde e beleza", "Cuidados com a saúde", "Acupuntura", "Agulhas de acupuntura"),
			array("5850", "Saúde e beleza", "Cuidados com a saúde", "Acupuntura", "Modelos de acupuntura"),
			array("5690", "Saúde e beleza", "Cuidados com a saúde", "Aparelhos auditivos"),
			array("8105", "Saúde e beleza", "Cuidados com a saúde", "Ataduras elásticas para amputados"),
			array("517", "Saúde e beleza", "Cuidados com a saúde", "Auxiliares à incontinência"),
			array("7002", "Saúde e beleza", "Cuidados com a saúde", "Caixas de contraceptivos"),
			array("3777", "Saúde e beleza", "Cuidados com a saúde", "Caixinhas de remédios"),
			array("7220", "Saúde e beleza", "Cuidados com a saúde", "Comadres"),
			array("4551", "Saúde e beleza", "Cuidados com a saúde", "Cuidados respiratórios"),
			array("7317", "Saúde e beleza", "Cuidados com a saúde", "Cuidados respiratórios", "Aparelhos de PAP (pressão positiva nas vias aéreas)"),
			array("505669", "Saúde e beleza", "Cuidados com a saúde", "Cuidados respiratórios", "Inaladores de vapor"),
			array("7316", "Saúde e beleza", "Cuidados com a saúde", "Cuidados respiratórios", "Máscaras de PAP (pressão positiva nas vias aéreas)"),
			array("4552", "Saúde e beleza", "Cuidados com a saúde", "Cuidados respiratórios", "Nebulizadores"),
			array("499692", "Saúde e beleza", "Cuidados com a saúde", "Cuidados respiratórios", "Tanques de oxigênio para uso médico"),
			array("5870", "Saúde e beleza", "Cuidados com a saúde", "Equipamentos de fisioterapia"),
			array("505352", "Saúde e beleza", "Cuidados com a saúde", "Equipamentos de fisioterapia", "Balanços terapêuticos"),
			array("8541", "Saúde e beleza", "Cuidados com a saúde", "Equipamentos de fisioterapia", "Estimuladores musculares elétricos"),
			array("7186", "Saúde e beleza", "Cuidados com a saúde", "Espermicidas"),
			array("5965", "Saúde e beleza", "Cuidados com a saúde", "Etiquetas de identificação hospitalar"),
			array("505820", "Saúde e beleza", "Cuidados com a saúde", "Loções e géis condutores"),
			array("5923", "Saúde e beleza", "Cuidados com a saúde", "Lubrificantes cirúrgicos"),
			array("500087", "Saúde e beleza", "Cuidados com a saúde", "Lâmpadas para luminoterapia"),
			array("518", "Saúde e beleza", "Cuidados com a saúde", "Medicamentos"),
			array("519", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade"),
			array("521", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Acessórios para equipamento de acessibilidade"),
			array("6929", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Acessórios de auxílio para locomoção"),
			array("5164", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Auxílios para locomoção"),
			array("5166", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Auxílios para locomoção", "Andadores"),
			array("5165", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Auxílios para locomoção", "Bengalas"),
			array("4248", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Auxílios para locomoção", "Muletas"),
			array("520", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Equipamento de acessibilidade"),
			array("3364", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Equipamento de acessibilidade", "Cadeiras de rodas"),
			array("7138", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Equipamento de acessibilidade", "Cadeiras elevadoras"),
			array("502969", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Equipamento de acessibilidade", "Placas e lençóis para transferência de pacientes"),
			array("3512", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Equipamento de acessibilidade", "Scooters elétricos"),
			array("5488", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Móveis e utensílios de acessibilidade"),
			array("7243", "Saúde e beleza", "Cuidados com a saúde", "Mobilidade e acessibilidade", "Móveis e utensílios de acessibilidade", "Bancos e assentos para banho"),
			array("494", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos"),
			array("497", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Analisadores de colesterol"),
			array("496", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Analisadores de gordura"),
			array("2633", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Bafômetro"),
			array("500", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Balanças de banheiro"),
			array("2246", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Medidores de glicose"),
			array("4767", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Monitores cardíacos para pré-natal"),
			array("500009", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Monitores de atividade"),
			array("495", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Monitores de pressão"),
			array("5551", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Oxímetros de pulso"),
			array("501", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Termômetros médicos"),
			array("505822", "Saúde e beleza", "Cuidados com a saúde", "Monitores biométricos", "Testes de ovulação e monitores de fertilidade"),
			array("2890", "Saúde e beleza", "Cuidados com a saúde", "Preparo físico e nutrição"),
			array("2984", "Saúde e beleza", "Cuidados com a saúde", "Preparo físico e nutrição", "Barras nutritivas"),
			array("5702", "Saúde e beleza", "Cuidados com a saúde", "Preparo físico e nutrição", "Bebidas que substituem refeições"),
			array("6242", "Saúde e beleza", "Cuidados com a saúde", "Preparo físico e nutrição", "Géis e mastigáveis nutritivos"),
			array("6871", "Saúde e beleza", "Cuidados com a saúde", "Preparo físico e nutrição", "Purês"),
			array("7413", "Saúde e beleza", "Cuidados com a saúde", "Preparo físico e nutrição", "Suplementos para alimentação por sonda"),
			array("525", "Saúde e beleza", "Cuidados com a saúde", "Preparo físico e nutrição", "Vitaminas e suplementos"),
			array("775", "Saúde e beleza", "Cuidados com a saúde", "Preservativos"),
			array("508", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros"),
			array("2954", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros", "Antissépticos e suprimentos para limpeza"),
			array("509", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros", "Bandagens e fitas"),
			array("510", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros", "Kits de primeiros socorros"),
			array("6206", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros", "Protetores de gesso e ataduras"),
			array("4527", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros", "Suprimentos de soluções para lavar os olhos"),
			array("516", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros", "Tratamentos a frio e a quente"),
			array("6205", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros", "Tratamentos a frio e a quente", "Almofadas de aquecimento"),
			array("5848", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros", "Tratamentos a frio e a quente", "Alívio contra dores musculares, linimentos"),
			array("4753", "Saúde e beleza", "Cuidados com a saúde", "Primeiros socorros", "Tratamentos a frio e a quente", "Sacos de gelo"),
			array("8082", "Saúde e beleza", "Cuidados com a saúde", "Recipientes de coleta"),
			array("5966", "Saúde e beleza", "Cuidados com a saúde", "Sistemas de alarme hospitalar"),
			array("523", "Saúde e beleza", "Cuidados com a saúde", "Suportes e aparelhos ortodônticos"),
			array("505293", "Saúde e beleza", "Cuidados com a saúde", "Testes médicos"),
			array("7337", "Saúde e beleza", "Cuidados com a saúde", "Testes médicos", "Kits de exame de tipagem sanguínea"),
			array("499934", "Saúde e beleza", "Cuidados com a saúde", "Testes médicos", "Kits para testes alérgicos"),
			array("7336", "Saúde e beleza", "Cuidados com a saúde", "Testes médicos", "Testes de HIV"),
			array("2552", "Saúde e beleza", "Cuidados com a saúde", "Testes médicos", "Testes de droga"),
			array("1680", "Saúde e beleza", "Cuidados com a saúde", "Testes médicos", "Testes de gravidez"),
			array("505294", "Saúde e beleza", "Cuidados com a saúde", "Testes médicos", "Testes de infecções do trato urinário"),
			array("2915", "Saúde e beleza", "Cuidados pessoais"),
			array("4076", "Saúde e beleza", "Cuidados pessoais", "Auxiliares do sono"),
			array("4056", "Saúde e beleza", "Cuidados pessoais", "Auxiliares do sono", "Máquinas de sons para relaxar e dormir"),
			array("4313", "Saúde e beleza", "Cuidados pessoais", "Auxiliares do sono", "Máscaras para dormir"),
			array("6017", "Saúde e beleza", "Cuidados pessoais", "Auxiliares do sono", "Soluções para o ronco e a apneia do sono"),
			array("4211", "Saúde e beleza", "Cuidados pessoais", "Auxiliares do sono", "Travesseiros de viagem"),
			array("528", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento"),
			array("6842", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Acessórios para aparadores de cabelo"),
			array("531", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Acessórios para barbeadores elétricos"),
			array("532", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Barbeadores elétricos"),
			array("8214", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Clareadores de pelos para o corpo e rosto"),
			array("2971", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Cremes de barbear"),
			array("4507", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Depilação"),
			array("4509", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Depilação", "Aparelhos de eletrólise"),
			array("7199", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Depilação", "Aparelhos para remoção de pelos a laser"),
			array("8136", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Depilação", "Aquecedores de cera para depilação"),
			array("4508", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Depilação", "Cremes depilatórios"),
			array("4510", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Depilação", "Depiladores"),
			array("4511", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Depilação", "Kits e suprimentos para depilação com cera"),
			array("5111", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Kits de barbear"),
			array("529", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Loção pós-barba"),
			array("2508", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Lápis vasoconstritor"),
			array("533", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Máquinas e tesouras para cortar cabelo"),
			array("534", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Navalhas e lâminas de barbear"),
			array("2681", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Pincéis de barba"),
			array("8531", "Saúde e beleza", "Cuidados pessoais", "Barbearia e embelezamento", "Tigelas e canecas de barbear"),
			array("6921", "Saúde e beleza", "Cuidados pessoais", "Barracas de bronzeamento artificial"),
			array("4929", "Saúde e beleza", "Cuidados pessoais", "Bolas de algodão"),
			array("473", "Saúde e beleza", "Cuidados pessoais", "Cosméticos"),
			array("474", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo"),
			array("3691", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Desinfetante de mãos"),
			array("2876", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Escovas de banho"),
			array("2875", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Esponjas e escovas de banho"),
			array("499913", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Lenços umedecidos para adultos"),
			array("2503", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Sabonete"),
			array("7417", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Sabonete em pó para as mãos"),
			array("3208", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Sabonete líquido para as mãos"),
			array("2747", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Sabonetes para o corpo"),
			array("2522", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Sais de banho e banho de espuma"),
			array("4049", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Banho e corpo", "Toucas de banho"),
			array("475", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cestas de presentes para o corpo e rosto"),
			array("6069", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Conjuntos de maquiagem"),
			array("567", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele"),
			array("2844", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Bloqueadores solares"),
			array("2592", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Creme hidratante"),
			array("2526", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Cremes de limpeza para o rosto"),
			array("482", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Cuidados com os lábios"),
			array("7429", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Kits anti-idade de cuidados com a pele"),
			array("7467", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Kits para limpeza facial"),
			array("6791", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Limpa-poros faciais"),
			array("8029", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Máscara comprimida para cuidado da pele"),
			array("6262", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Máscaras e peelings faciais"),
			array("2740", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Produtos para bronzeamento"),
			array("5338", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Produtos para bronzeamento", "Autobronzeador"),
			array("5339", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Produtos para bronzeamento", "Óleo bronzeador"),
			array("6034", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Removedores de maquiagem"),
			array("6863", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Removedores de verrugas"),
			array("5820", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Repelente de insetos"),
			array("5980", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Talco"),
			array("5976", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Tonificantes e adstringentes"),
			array("481", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Tratamentos e kits para acne"),
			array("6753", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Vaselina"),
			array("6104", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com a pele", "Óleos corporais"),
			array("478", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com as unhas"),
			array("6893", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com as unhas", "Cola para unhas"),
			array("3009", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com as unhas", "Cremes e óleos para cutículas"),
			array("7445", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com as unhas", "Diluente para esmalte"),
			array("2683", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com as unhas", "Esmaltes"),
			array("233419", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com as unhas", "Gotas e sprays secantes para as unhas"),
			array("5975", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com as unhas", "Kits e acessórios de Nail Art"),
			array("2946", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com as unhas", "Removedores de esmalte"),
			array("4218", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Cuidados com as unhas", "Unhas postiças"),
			array("2619", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas"),
			array("2548", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem"),
			array("502996", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Acessórios para cílios postiços"),
			array("7493", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Acessórios para cílios postiços", "Aplicadores para cílios postiços"),
			array("7256", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Acessórios para cílios postiços", "Cola para cílios postiços"),
			array("502997", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Acessórios para cílios postiços", "Removedor de cílios postiços"),
			array("2780", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Curvex"),
			array("476", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Espelhos de maquiagem"),
			array("4106", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Esponjas de maquiagem"),
			array("499822", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Estojos de maquiagem com refil"),
			array("7356", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Fita e cola para pálpebra dupla"),
			array("4121", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Mata-borrão facial"),
			array("6555", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Moldes para sobrancelha"),
			array("3025", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Pincéis de maquiagem"),
			array("6282", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas de maquiagem", "Refis para curvex"),
			array("2958", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para cuidados com a pele"),
			array("499926", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para cuidados com a pele", "Aplicadores de loção e filtro solar"),
			array("8132", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para cuidados com a pele", "Cabeças de escovas para limpeza de pele"),
			array("7190", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para cuidados com a pele", "Lixa para pés"),
			array("2511", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para cuidados com a pele", "Pedras-pomes"),
			array("6261", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para cuidados com a pele", "Removedores de impurezas"),
			array("7018", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para cuidados com a pele", "Rolos dermatológicos"),
			array("6760", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para cuidados com a pele", "Saunas faciais"),
			array("6260", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para cuidados com a pele", "Sistemas e pincéis de limpeza de pele"),
			array("2975", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas"),
			array("499698", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Acessórios de lixa elétrica"),
			array("3037", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Alicates de cutículas"),
			array("6300", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Conjuntos de utensílios para manicure"),
			array("2828", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Cortadores de unhas"),
			array("2739", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Empurradores de cutículas"),
			array("7490", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Lixa elétrica de unha"),
			array("2734", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Lixas comuns e lixas metálicas de unhas"),
			array("6341", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Polidores de unhas"),
			array("5880", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Secadores de unhas"),
			array("7494", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Ferramentas cosméticas", "Ferramentas para unhas", "Separador de dedos para pedicure"),
			array("6331", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Limpadores de utensílios cosméticos"),
			array("477", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem"),
			array("5978", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem corporal"),
			array("5979", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem corporal", "Bases e tintas corporais"),
			array("5981", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem corporal", "Glitter para o corpo e cabelo"),
			array("4779", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para fantasia e teatro"),
			array("2571", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para o rosto"),
			array("2765", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para o rosto", "Bases e corretivos"),
			array("6305", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para o rosto", "Blushes e bronzers"),
			array("6304", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para o rosto", "Iluminadores"),
			array("8218", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para o rosto", "Primers faciais"),
			array("2980", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para o rosto", "Pó facial"),
			array("2645", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os lábios"),
			array("3021", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os lábios", "Batons"),
			array("2858", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os lábios", "Brilhos labiais"),
			array("6306", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os lábios", "Corantes para bochecha e lábios"),
			array("2589", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os lábios", "Delineador labial"),
			array("8217", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os lábios", "Primers labiais"),
			array("2779", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os olhos"),
			array("2761", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os olhos", "Cílios postiços"),
			array("2807", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os olhos", "Delineador para olhos"),
			array("2686", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os olhos", "Lápis para sobrancelhas"),
			array("8220", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os olhos", "Primer para olhos"),
			array("8219", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os olhos", "Primers de máscara para cílios"),
			array("2834", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os olhos", "Rímel"),
			array("2904", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os olhos", "Sombras"),
			array("6340", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Maquiagem para os olhos", "Tratamentos para crescimento dos cílios e das sobrancelhas"),
			array("6072", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Sprays de acabamento para maquiagem"),
			array("3509", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Maquiagem", "Tatuagens temporárias"),
			array("479", "Saúde e beleza", "Cuidados pessoais", "Cosméticos", "Perfume e colônia"),
			array("2934", "Saúde e beleza", "Cuidados pessoais", "Cotonetes"),
			array("526", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais"),
			array("4775", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Acessórios para escova de dente"),
			array("4776", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Acessórios para escova de dente", "Cabeças de reposição para escovas de dente"),
			array("6920", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Acessórios para escova de dente", "Capas para escovas de dente"),
			array("4942", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Acessórios para escova de dente", "Desinfetantes para escovas de dente"),
			array("5155", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Adesivos para dentadura"),
			array("3040", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Antisséptico bucal"),
			array("3019", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Branqueadores dentais"),
			array("2527", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Dentaduras"),
			array("527", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Escovas de dente"),
			array("5154", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Espremedores e suportes para pasta de dentes"),
			array("505367", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Estojos para aparelhos ortodônticos"),
			array("2620", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Fio-dental"),
			array("6715", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Fio-dental elétrico"),
			array("5295", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Jatos de água para limpeza bucal"),
			array("8543", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Kits de reparos para dentaduras"),
			array("6441", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Limpadores de língua"),
			array("5824", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Limpadores de próteses"),
			array("2769", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Massageadores de gengiva"),
			array("4316", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Palitos de dente"),
			array("1360", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Pasta de dente"),
			array("5823", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Protetores bucais"),
			array("6455", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Refis para jatos de água"),
			array("6189", "Saúde e beleza", "Cuidados pessoais", "Cuidados bucais", "Spray bucal"),
			array("1380", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão"),
			array("2521", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Acessórios para óculos"),
			array("8204", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Acessórios para óculos", "Correntes e cordões para óculos"),
			array("5507", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Acessórios para óculos", "Estojos e suportes para óculos"),
			array("352853", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Acessórios para óculos", "Soluções para limpeza de lentes"),
			array("2922", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Colírios e lubrificantes para olhos"),
			array("3011", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Cuidados com lentes de contato"),
			array("6510", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Cuidados com lentes de contato", "Caixas para lentes de contato"),
			array("7363", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Cuidados com lentes de contato", "Kit de cuidados para lentes de contato"),
			array("6509", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Cuidados com lentes de contato", "Soluções para lentes de contato"),
			array("2923", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Lentes de contato"),
			array("2733", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Lentes para óculos"),
			array("6977", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Lentes para óculos de sol"),
			array("524", "Saúde e beleza", "Cuidados pessoais", "Cuidados com a visão", "Óculos"),
			array("493", "Saúde e beleza", "Cuidados pessoais", "Cuidados com as costas"),
			array("7404", "Saúde e beleza", "Cuidados pessoais", "Cuidados com as costas", "Almofadas de apoio para costas e lombar"),
			array("486", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos"),
			array("5977", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Acessórios para tintura de cabelo"),
			array("6018", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Acessórios para utensílios de penteado"),
			array("4569", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Acessórios para utensílios de penteado", "Acessórios para chapinhas"),
			array("4475", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Acessórios para utensílios de penteado", "Acessórios para secadores de cabelo"),
			array("5317", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Acessórios para utensílios de penteado", "Pregadores e rolos para cabelo"),
			array("6052", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Alisadores de cabelo"),
			array("6099", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Corretivos para perda de cabelo"),
			array("8452", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Kits de cuidados com os cabelos"),
			array("1901", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Produtos de penteado"),
			array("6053", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Removedores de tinta de cabelo"),
			array("3013", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Tesouras de cabelo"),
			array("2814", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Tintura para cabelo"),
			array("6429", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Toucas térmicas"),
			array("4766", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Tratamentos para calvície"),
			array("6019", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Utensílios de penteado"),
			array("488", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Utensílios de penteado", "Bobes"),
			array("3407", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Utensílios de penteado", "Chapinhas"),
			array("499992", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Utensílios de penteado", "Conjuntos de aparelhos para modelagem dos cabelos"),
			array("487", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Utensílios de penteado", "Pentes e escovas"),
			array("489", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Utensílios de penteado", "Pranchas modeladoras"),
			array("490", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Utensílios de penteado", "Secadores de cabelo"),
			array("2441", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os cabelos", "Xampu e condicionador"),
			array("506", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os ouvidos"),
			array("5706", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os ouvidos", "Cones de limpeza de ouvidos"),
			array("6562", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os ouvidos", "Kits de remoção de cera"),
			array("7542", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os ouvidos", "Porta tampões de ouvido"),
			array("500024", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os ouvidos", "Removedores de cera de ouvido"),
			array("6559", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os ouvidos", "Remédios para ouvidos"),
			array("6560", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os ouvidos", "Secadores de orelhas"),
			array("6561", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os ouvidos", "Seringas para ouvidos"),
			array("2596", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os ouvidos", "Tampões de ouvido"),
			array("515", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os pés"),
			array("3022", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os pés", "Cuidados com espigões e calos"),
			array("2992", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os pés", "Cuidados com joanetes"),
			array("3049", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os pés", "Desodorantes para os pés"),
			array("2801", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os pés", "Palmilhas e proteções para os pés"),
			array("7495", "Saúde e beleza", "Cuidados pessoais", "Cuidados com os pés", "Separador de dedos"),
			array("484", "Saúde e beleza", "Cuidados pessoais", "Desodorantes e antitranspirantes"),
			array("472", "Saúde e beleza", "Cuidados pessoais", "Esteiras de bronzeamento"),
			array("7134", "Saúde e beleza", "Cuidados pessoais", "Kits e suprimentos enema"),
			array("777", "Saúde e beleza", "Cuidados pessoais", "Lubrificantes pessoais"),
			array("5663", "Saúde e beleza", "Cuidados pessoais", "Massagem e relaxamento"),
			array("233420", "Saúde e beleza", "Cuidados pessoais", "Massagem e relaxamento", "Almofadas para os olhos"),
			array("8530", "Saúde e beleza", "Cuidados pessoais", "Massagem e relaxamento", "Aquecedores para pedras de massagem"),
			array("1442", "Saúde e beleza", "Cuidados pessoais", "Massagem e relaxamento", "Cadeiras de massagem"),
			array("500060", "Saúde e beleza", "Cuidados pessoais", "Massagem e relaxamento", "Coçadores de costas"),
			array("471", "Saúde e beleza", "Cuidados pessoais", "Massagem e relaxamento", "Massageadores"),
			array("2074", "Saúde e beleza", "Cuidados pessoais", "Massagem e relaxamento", "Mesas de massagem"),
			array("8135", "Saúde e beleza", "Cuidados pessoais", "Massagem e relaxamento", "Pedras de massagem"),
			array("5664", "Saúde e beleza", "Cuidados pessoais", "Massagem e relaxamento", "Óleos de massagem"),
			array("2656", "Saúde e beleza", "Cuidados pessoais", "Pinças"),
			array("485", "Saúde e beleza", "Cuidados pessoais", "Suprimentos para a higiene feminina"),
			array("2387", "Saúde e beleza", "Cuidados pessoais", "Suprimentos para a higiene feminina", "Absorventes e protetores femininos"),
			array("8122", "Saúde e beleza", "Cuidados pessoais", "Suprimentos para a higiene feminina", "Coletores menstruais"),
			array("6862", "Saúde e beleza", "Cuidados pessoais", "Suprimentos para a higiene feminina", "Desodorantes femininos"),
			array("5821", "Saúde e beleza", "Cuidados pessoais", "Suprimentos para a higiene feminina", "Produtos para higiene íntima"),
			array("2564", "Saúde e beleza", "Cuidados pessoais", "Suprimentos para a higiene feminina", "Tampões"),
			array("5573", "Saúde e beleza", "Limpeza e cuidado de jóias"),
			array("500082", "Saúde e beleza", "Limpeza e cuidado de jóias", "Ferramentas para limpeza de joias"),
			array("5124", "Saúde e beleza", "Limpeza e cuidado de jóias", "Kits para conserto de relógios"),
			array("500083", "Saúde e beleza", "Limpeza e cuidado de jóias", "Limpadores a vapor para joias"),
			array("5974", "Saúde e beleza", "Limpeza e cuidado de jóias", "Porta-jóias"),
			array("499919", "Saúde e beleza", "Limpeza e cuidado de jóias", "Produtos para limpeza e polimento de joias")
		);
	}

	private function compare_strings($a, $b){
		$str = array(
			preg_replace(array("/(á|à|ã|â|ä)/","/(Á|À|Ã|Â|Ä)/","/(é|è|ê|ë)/","/(É|È|Ê|Ë)/","/(í|ì|î|ï)/","/(Í|Ì|Î|Ï)/","/(ó|ò|õ|ô|ö)/","/(Ó|Ò|Õ|Ô|Ö)/","/(ú|ù|û|ü)/","/(Ú|Ù|Û|Ü)/","/(ñ)/","/(Ñ)/","/(ç)/","/(Ç)/"),explode(" ","a A e E i I o O u U n N c C"),$a),
			preg_replace(array("/(á|à|ã|â|ä)/","/(Á|À|Ã|Â|Ä)/","/(é|è|ê|ë)/","/(É|È|Ê|Ë)/","/(í|ì|î|ï)/","/(Í|Ì|Î|Ï)/","/(ó|ò|õ|ô|ö)/","/(Ó|Ò|Õ|Ô|Ö)/","/(ú|ù|û|ü)/","/(Ú|Ù|Û|Ü)/","/(ñ)/","/(Ñ)/","/(ç)/","/(Ç)/"),explode(" ","a A e E i I o O u U n N c C"),$b)
		);

		return ~~(((similar_text(preg_replace("/[^0-9a-z]/", "", strtolower($str[0])),preg_replace("/[^0-9a-z]/", "", strtolower($str[1]))) + 1) / (max(strlen($str[0]),strlen($str[1]),1)+1) * 110));
	}

	function find(Array $queries, $precision = 100, $factor = 4){
		for($f = min(80,$precision * $factor); $f > max(10,round($precision / $factor)); $f -= 2){
			foreach($queries as $query){
				for($i = 0; $i < count($this->categories); $i++){
					$category = $this->categories[$i];

					$id = array_shift($category);

					for($j = 0; $j < count($category); $j++){
						if(($this->compare_strings($query, $category[$j])) >= min(80,$precision * $factor)){
							return implode(" > ", $category);
						}
					}
				}
			}
		}

		for($f = 80; $f > 50; $f -= 10){
			foreach($queries as $query){
				for($i = 0; $i < count($this->categories); $i++){
					$category = $this->categories[$i];

					$id = array_shift($category);

					for($j = 0; $j < count($category); $j++){
						$split = [explode(" ", $query), explode(" ", $category[$j])];
						for($k = 0; $k < count($split[0]); $k++){
							for($l = 0; $l < count($split[1]); $l++){
								if(($this->compare_strings($split[0][$k], $split[1][$l])) >= min(80,$precision * $factor)){
									return implode(" > ", $category);
								}
							}
						}
					}
				}
			}
		}
		return 0;
	}
} ?>
